import { hydrogenRoutes } from '@shopify/hydrogen';
import { route, index, type RouteConfig } from '@react-router/dev/routes';

export default hydrogenRoutes([
  index('routes/_index.tsx'),
  route('ar', 'routes/ar._index.tsx', { id: 'ar-index' }),
  route('ar/collections/:handle', 'routes/collections.$handle.tsx', { id: 'ar-collections-handle' }),
  route('ar/products/:handle', 'routes/products.$handle.tsx', { id: 'ar-products-handle' }),
  route('ar/search', 'routes/search.tsx', { id: 'ar-search' }),
  route('ar/blogs/all', 'routes/blogs.all.tsx', { id: 'ar-blogs-all' }),
  route('ar/blogs/:handle', 'routes/blogs.$handle.tsx', { id: 'ar-blogs-handle' }),
  route('ar/blogs/:blogHandle/:articleHandle', 'routes/blogs.$blogHandle.$articleHandle.tsx', { id: 'ar-blogs-article' }),
  route('ar/pages/customer-reviews', 'routes/pages.customer-reviews.tsx', { id: 'ar-pages-customer-reviews' }),
  route('ar/pages/تقييمات-العملاء', 'routes/pages.customer-reviews.tsx', { id: 'ar-pages-customer-reviews-ar' }),
  route('ar/pages/contact-us', 'routes/pages.contact.tsx', { id: 'ar-pages-contact' }),
  route('ar/pages/اتصل-بنا-1', 'routes/pages.contact.tsx', { id: 'ar-pages-contact-ar' }),
  route('ar/pages/refund-exchange', 'routes/pages.refund-exchange.tsx', { id: 'ar-pages-refund' }),
  route('ar/pages/استرداد-الأموال-أو-التبديل', 'routes/pages.refund-exchange.tsx', { id: 'ar-pages-refund-ar' }),
  route('ar/pages/rewards', 'routes/pages.rewards.tsx', { id: 'ar-pages-rewards' }),
  route('ar/pages/مكافأت', 'routes/pages.rewards.tsx', { id: 'ar-pages-rewards-ar' }),
  route('ar/pages/mls-rewards', 'routes/pages.mls-rewards.tsx', { id: 'ar-pages-mls-rewards' }),
  route('ar/pages/مكافآت-mls', 'routes/pages.mls-rewards.tsx', { id: 'ar-pages-mls-rewards-ar' }),
  route('ar/pages/all-blog', 'routes/pages.all-blog.tsx', { id: 'ar-pages-all-blog' }),
  route('ar/pages/refer-a-friend', 'routes/pages.refer-a-friend.tsx', { id: 'ar-pages-refer' }),
  route('ar/pages/أح-ل-صديق-ا', 'routes/pages.refer-a-friend.tsx', { id: 'ar-pages-refer-ar' }),
  route('ar/pages/faqs', 'routes/pages.faqs.tsx', { id: 'ar-pages-faqs' }),
  route('ar/pages/أسئلة-وأجوبة', 'routes/pages.faqs.tsx', { id: 'ar-pages-faqs-ar' }),
  route('ar/pages/mls-gourmet', 'routes/pages.mls-gourmet.tsx', { id: 'ar-pages-gourmet' }),
  route('ar/pages/إم-إل-إس-جورميه', 'routes/pages.mls-gourmet.tsx', { id: 'ar-pages-gourmet-ar' }),
  route('ar/pages/our-story-new', 'routes/pages.our-story-new.tsx', { id: 'ar-pages-our-story' }),
  route('ar/pages/قصتنا-جديدة', 'routes/pages.our-story-new.tsx', { id: 'ar-pages-our-story-ar' }),
  route('ar/pages/mls-affiliate', 'routes/pages.mls-affiliate.tsx', { id: 'ar-pages-affiliate' }),
  route('ar/pages/شريك-mls', 'routes/pages.mls-affiliate.tsx', { id: 'ar-pages-affiliate-ar' }),
  route('ar/pages/delivery-info', 'routes/pages.delivery-info.tsx', { id: 'ar-pages-delivery' }),
  route('ar/pages/معلومات-التوصيل', 'routes/pages.delivery-info.tsx', { id: 'ar-pages-delivery-ar' }),
  route('ar/pages/subscription-policy', 'routes/pages.subscription-policy.tsx', { id: 'ar-pages-sub-policy' }),
  route('ar/pages/سياسة-الاشتراك', 'routes/pages.subscription-policy.tsx', { id: 'ar-pages-sub-policy-ar' }),
  route('ar/pages/subscriptions', 'routes/pages.subscriptions.tsx', { id: 'ar-pages-subscriptions' }),
  route('ar/pages/الاشتراكات', 'routes/pages.subscriptions.tsx', { id: 'ar-pages-subscriptions-ar' }),
  route('ar/pages/subscription', 'routes/pages.subscription.tsx', { id: 'ar-pages-subscription' }),
  route('ar/pages/اشتراك', 'routes/pages.subscription.tsx', { id: 'ar-pages-subscription-ar' }),
  route('ar/pages/:handle', 'routes/pages.$handle.tsx', { id: 'ar-pages-handle' }),
  route('ar/*', 'routes/ar.$.tsx'),
  route('cart', 'routes/cart.tsx'),
  route('cart.js', 'routes/cart[.]js.tsx'),
  route('apps/loggedincustomer', 'routes/apps.loggedincustomer.tsx'),
  route('apps/pushowl/sdks/service-worker.js', 'routes/apps.pushowl.sdks.service-worker[.]js.tsx'),
  route('sitemap.xml', 'routes/sitemap[.]xml.tsx'),
  route('sitemap_products.xml', 'routes/sitemap-resource.tsx', { id: 'sm-products' }),
  route('sitemap_collections.xml', 'routes/sitemap-resource.tsx', { id: 'sm-collections' }),
  route('sitemap_pages.xml', 'routes/sitemap-resource.tsx', { id: 'sm-pages' }),
  route('sitemap_blogs.xml', 'routes/sitemap-resource.tsx', { id: 'sm-blogs' }),
  route('ar/sitemap_products.xml', 'routes/sitemap-resource.tsx', { id: 'sm-ar-products' }),
  route('ar/sitemap_collections.xml', 'routes/sitemap-resource.tsx', { id: 'sm-ar-collections' }),
  route('ar/sitemap_blogs.xml', 'routes/sitemap-resource.tsx', { id: 'sm-ar-blogs' }),
  route('robots.txt', 'routes/robots[.]txt.tsx'),
  route('llms.txt', 'routes/llms[.]txt.tsx'),
  route('customer_authentication/redirect', 'routes/customer_authentication.redirect.tsx'),
  route('search', 'routes/search.tsx', { id: 'search' }),
  route('collections', 'routes/collections._index.tsx'),
  route('collections/:handle', 'routes/collections.$handle.tsx'),
  route('collections/:collectionHandle/products/:productHandle', 'routes/products.$handle.tsx', { id: 'collection-product' }),
  route('blogs/all', 'routes/blogs.all.tsx'),
  route('blogs/:handle', 'routes/blogs.$handle.tsx'),
  route('blogs/:blogHandle/:articleHandle', 'routes/blogs.$blogHandle.$articleHandle.tsx'),
  route('products/:handle', 'routes/products.$handle.tsx'),
  route('api/reviews/store', 'routes/api.reviews.store.tsx'),
  route('api/reviews/:handle', 'routes/api.reviews.$handle.tsx'),
  route('api/selling-plans/:handle', 'routes/api.selling-plans.$handle.tsx'),
  route('api/globo-options/:productId', 'routes/api.globo-options.$productId.tsx'),
  route('api/back-in-stock', 'routes/api.back-in-stock.tsx'),
  route('api/discounts', 'routes/api.discounts.ts'),
  route('pages/customer-reviews', 'routes/pages.customer-reviews.tsx'),
  route('pages/contact-us', 'routes/pages.contact.tsx'),
  route('pages/refund-exchange', 'routes/pages.refund-exchange.tsx'),
  route('pages/rewards', 'routes/pages.rewards.tsx'),
  route('pages/mls-rewards', 'routes/pages.mls-rewards.tsx'),
  route('pages/all-blog', 'routes/pages.all-blog.tsx'),
  route('pages/refer-a-friend', 'routes/pages.refer-a-friend.tsx'),
  route('pages/faqs', 'routes/pages.faqs.tsx'),
  route('pages/mls-gourmet', 'routes/pages.mls-gourmet.tsx'),
  route('pages/our-story-new', 'routes/pages.our-story-new.tsx'),
  route('pages/mls-affiliate', 'routes/pages.mls-affiliate.tsx'),
  route('pages/delivery-info', 'routes/pages.delivery-info.tsx'),
  route('pages/subscription-policy', 'routes/pages.subscription-policy.tsx'),
  route('pages/subscriptions', 'routes/pages.subscriptions.tsx'),
  route('pages/subscription', 'routes/pages.subscription.tsx'),
  route('pages/:handle', 'routes/pages.$handle.tsx'),
  route('account/login', 'routes/account_.login.tsx'),
  route('account/authorize', 'routes/account_.authorize.tsx'),
  route('account/logout', 'routes/account_.logout.tsx'),
  route('account', 'routes/account.tsx', [
    index('routes/account._index.tsx'),
  ]),
]) satisfies RouteConfig;
