// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/cart.js": {
    params: {};
  };
  "/apps/loggedincustomer": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/api/reviews/store": {
    params: {};
  };
  "/api/reviews/:handle": {
    params: {
      "handle": string;
    };
  };
  "/api/selling-plans/:handle": {
    params: {
      "handle": string;
    };
  };
  "/api/globo-options/:productId": {
    params: {
      "productId": string;
    };
  };
  "/pages/customer-reviews": {
    params: {};
  };
  "/pages/contact-us": {
    params: {};
  };
  "/pages/refund-exchange": {
    params: {};
  };
  "/pages/rewards": {
    params: {};
  };
  "/pages/faqs": {
    params: {};
  };
  "/pages/mls-gourmet": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account": {
    params: {};
  };
  "/account/authorize": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/cart" | "/cart.js" | "/apps/loggedincustomer" | "/search" | "/collections/:handle" | "/products/:handle" | "/api/reviews/store" | "/api/reviews/:handle" | "/api/selling-plans/:handle" | "/api/globo-options/:productId" | "/pages/customer-reviews" | "/pages/contact-us" | "/pages/refund-exchange" | "/pages/rewards" | "/pages/faqs" | "/pages/mls-gourmet" | "/pages/:handle" | "/account" | "/account/authorize" | "/account/logout" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/cart[.]js.tsx": {
    id: "routes/cart[.]js";
    page: "/cart.js";
  };
  "routes/apps.loggedincustomer.tsx": {
    id: "routes/apps.loggedincustomer";
    page: "/apps/loggedincustomer";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/api.reviews.store.tsx": {
    id: "routes/api.reviews.store";
    page: "/api/reviews/store";
  };
  "routes/api.reviews.$handle.tsx": {
    id: "routes/api.reviews.$handle";
    page: "/api/reviews/:handle";
  };
  "routes/api.selling-plans.$handle.tsx": {
    id: "routes/api.selling-plans.$handle";
    page: "/api/selling-plans/:handle";
  };
  "routes/api.globo-options.$productId.tsx": {
    id: "routes/api.globo-options.$productId";
    page: "/api/globo-options/:productId";
  };
  "routes/pages.customer-reviews.tsx": {
    id: "routes/pages.customer-reviews";
    page: "/pages/customer-reviews";
  };
  "routes/pages.contact.tsx": {
    id: "routes/pages.contact";
    page: "/pages/contact-us";
  };
  "routes/pages.refund-exchange.tsx": {
    id: "routes/pages.refund-exchange";
    page: "/pages/refund-exchange";
  };
  "routes/pages.rewards.tsx": {
    id: "routes/pages.rewards";
    page: "/pages/rewards";
  };
  "routes/pages.faqs.tsx": {
    id: "routes/pages.faqs";
    page: "/pages/faqs";
  };
  "routes/pages.mls-gourmet.tsx": {
    id: "routes/pages.mls-gourmet";
    page: "/pages/mls-gourmet";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/authorize" | "/account/logout";
  };
  "routes/account._index.tsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "../../../..//Headless loveable code/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Headless loveable code/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../../../..//Headless loveable code/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../../../..//Headless loveable code/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../../../..//Headless loveable code/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../../../..//Headless loveable code/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/cart[.]js": typeof import("./app/routes/cart[.]js.tsx");
  "routes/apps.loggedincustomer": typeof import("./app/routes/apps.loggedincustomer.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/api.reviews.store": typeof import("./app/routes/api.reviews.store.tsx");
  "routes/api.reviews.$handle": typeof import("./app/routes/api.reviews.$handle.tsx");
  "routes/api.selling-plans.$handle": typeof import("./app/routes/api.selling-plans.$handle.tsx");
  "routes/api.globo-options.$productId": typeof import("./app/routes/api.globo-options.$productId.tsx");
  "routes/pages.customer-reviews": typeof import("./app/routes/pages.customer-reviews.tsx");
  "routes/pages.contact": typeof import("./app/routes/pages.contact.tsx");
  "routes/pages.refund-exchange": typeof import("./app/routes/pages.refund-exchange.tsx");
  "routes/pages.rewards": typeof import("./app/routes/pages.rewards.tsx");
  "routes/pages.faqs": typeof import("./app/routes/pages.faqs.tsx");
  "routes/pages.mls-gourmet": typeof import("./app/routes/pages.mls-gourmet.tsx");
  "routes/pages.$handle": typeof import("./app/routes/pages.$handle.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account._index": typeof import("./app/routes/account._index.tsx");
  "routes/account_.authorize": typeof import("./app/routes/account_.authorize.tsx");
  "routes/account_.logout": typeof import("./app/routes/account_.logout.tsx");
  "/Headless loveable code/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};