// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/ar": {
    params: {};
  };
  "/ar/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/ar/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/ar/search": {
    params: {};
  };
  "/ar/blogs/all": {
    params: {};
  };
  "/ar/blogs/:handle": {
    params: {
      "handle": string;
    };
  };
  "/ar/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/ar/pages/customer-reviews": {
    params: {};
  };
  "/ar/pages/contact-us": {
    params: {};
  };
  "/ar/pages/refund-exchange": {
    params: {};
  };
  "/ar/pages/rewards": {
    params: {};
  };
  "/ar/pages/mls-rewards": {
    params: {};
  };
  "/ar/pages/all-blog": {
    params: {};
  };
  "/ar/pages/refer-a-friend": {
    params: {};
  };
  "/ar/pages/faqs": {
    params: {};
  };
  "/ar/pages/mls-gourmet": {
    params: {};
  };
  "/ar/pages/our-story-new": {
    params: {};
  };
  "/ar/pages/mls-affiliate": {
    params: {};
  };
  "/ar/pages/delivery-info": {
    params: {};
  };
  "/ar/pages/subscription-policy": {
    params: {};
  };
  "/ar/pages/subscriptions": {
    params: {};
  };
  "/ar/pages/subscription": {
    params: {};
  };
  "/ar/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/ar/*": {
    params: {
      "*": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/cart.js": {
    params: {};
  };
  "/apps/loggedincustomer": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/blogs/all": {
    params: {};
  };
  "/blogs/:handle": {
    params: {
      "handle": string;
    };
  };
  "/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/api/reviews/store": {
    params: {};
  };
  "/api/reviews/:handle": {
    params: {
      "handle": string;
    };
  };
  "/api/selling-plans/:handle": {
    params: {
      "handle": string;
    };
  };
  "/api/globo-options/:productId": {
    params: {
      "productId": string;
    };
  };
  "/api/back-in-stock": {
    params: {};
  };
  "/pages/customer-reviews": {
    params: {};
  };
  "/pages/contact-us": {
    params: {};
  };
  "/pages/refund-exchange": {
    params: {};
  };
  "/pages/rewards": {
    params: {};
  };
  "/pages/mls-rewards": {
    params: {};
  };
  "/pages/all-blog": {
    params: {};
  };
  "/pages/refer-a-friend": {
    params: {};
  };
  "/pages/faqs": {
    params: {};
  };
  "/pages/mls-gourmet": {
    params: {};
  };
  "/pages/our-story-new": {
    params: {};
  };
  "/pages/mls-affiliate": {
    params: {};
  };
  "/pages/delivery-info": {
    params: {};
  };
  "/pages/subscription-policy": {
    params: {};
  };
  "/pages/subscriptions": {
    params: {};
  };
  "/pages/subscription": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account": {
    params: {};
  };
  "/account/authorize": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/ar" | "/ar/collections/:handle" | "/ar/products/:handle" | "/ar/search" | "/ar/blogs/all" | "/ar/blogs/:handle" | "/ar/blogs/:blogHandle/:articleHandle" | "/ar/pages/customer-reviews" | "/ar/pages/contact-us" | "/ar/pages/refund-exchange" | "/ar/pages/rewards" | "/ar/pages/mls-rewards" | "/ar/pages/all-blog" | "/ar/pages/refer-a-friend" | "/ar/pages/faqs" | "/ar/pages/mls-gourmet" | "/ar/pages/our-story-new" | "/ar/pages/mls-affiliate" | "/ar/pages/delivery-info" | "/ar/pages/subscription-policy" | "/ar/pages/subscriptions" | "/ar/pages/subscription" | "/ar/pages/:handle" | "/ar/*" | "/cart" | "/cart.js" | "/apps/loggedincustomer" | "/search" | "/collections/:handle" | "/blogs/all" | "/blogs/:handle" | "/blogs/:blogHandle/:articleHandle" | "/products/:handle" | "/api/reviews/store" | "/api/reviews/:handle" | "/api/selling-plans/:handle" | "/api/globo-options/:productId" | "/api/back-in-stock" | "/pages/customer-reviews" | "/pages/contact-us" | "/pages/refund-exchange" | "/pages/rewards" | "/pages/mls-rewards" | "/pages/all-blog" | "/pages/refer-a-friend" | "/pages/faqs" | "/pages/mls-gourmet" | "/pages/our-story-new" | "/pages/mls-affiliate" | "/pages/delivery-info" | "/pages/subscription-policy" | "/pages/subscriptions" | "/pages/subscription" | "/pages/:handle" | "/account" | "/account/authorize" | "/account/logout" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/ar._index.tsx": {
    id: "ar-index";
    page: "/ar";
  };
  "routes/collections.$handle.tsx": {
    id: "ar-collections-handle";
    page: "/ar/collections/:handle";
  } | {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "ar-products-handle";
    page: "/ar/products/:handle";
  } | {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/search.tsx": {
    id: "ar-search";
    page: "/ar/search";
  } | {
    id: "search";
    page: "/search";
  };
  "routes/blogs.all.tsx": {
    id: "ar-blogs-all";
    page: "/ar/blogs/all";
  } | {
    id: "routes/blogs.all";
    page: "/blogs/all";
  };
  "routes/blogs.$handle.tsx": {
    id: "ar-blogs-handle";
    page: "/ar/blogs/:handle";
  } | {
    id: "routes/blogs.$handle";
    page: "/blogs/:handle";
  };
  "routes/blogs.$blogHandle.$articleHandle.tsx": {
    id: "ar-blogs-article";
    page: "/ar/blogs/:blogHandle/:articleHandle";
  } | {
    id: "routes/blogs.$blogHandle.$articleHandle";
    page: "/blogs/:blogHandle/:articleHandle";
  };
  "routes/pages.customer-reviews.tsx": {
    id: "ar-pages-customer-reviews";
    page: "/ar/pages/customer-reviews";
  } | {
    id: "routes/pages.customer-reviews";
    page: "/pages/customer-reviews";
  };
  "routes/pages.contact.tsx": {
    id: "ar-pages-contact";
    page: "/ar/pages/contact-us";
  } | {
    id: "routes/pages.contact";
    page: "/pages/contact-us";
  };
  "routes/pages.refund-exchange.tsx": {
    id: "ar-pages-refund";
    page: "/ar/pages/refund-exchange";
  } | {
    id: "routes/pages.refund-exchange";
    page: "/pages/refund-exchange";
  };
  "routes/pages.rewards.tsx": {
    id: "ar-pages-rewards";
    page: "/ar/pages/rewards";
  } | {
    id: "routes/pages.rewards";
    page: "/pages/rewards";
  };
  "routes/pages.mls-rewards.tsx": {
    id: "ar-pages-mls-rewards";
    page: "/ar/pages/mls-rewards";
  } | {
    id: "routes/pages.mls-rewards";
    page: "/pages/mls-rewards";
  };
  "routes/pages.all-blog.tsx": {
    id: "ar-pages-all-blog";
    page: "/ar/pages/all-blog";
  } | {
    id: "routes/pages.all-blog";
    page: "/pages/all-blog";
  };
  "routes/pages.refer-a-friend.tsx": {
    id: "ar-pages-refer";
    page: "/ar/pages/refer-a-friend";
  } | {
    id: "routes/pages.refer-a-friend";
    page: "/pages/refer-a-friend";
  };
  "routes/pages.faqs.tsx": {
    id: "ar-pages-faqs";
    page: "/ar/pages/faqs";
  } | {
    id: "routes/pages.faqs";
    page: "/pages/faqs";
  };
  "routes/pages.mls-gourmet.tsx": {
    id: "ar-pages-gourmet";
    page: "/ar/pages/mls-gourmet";
  } | {
    id: "routes/pages.mls-gourmet";
    page: "/pages/mls-gourmet";
  };
  "routes/pages.our-story-new.tsx": {
    id: "ar-pages-our-story";
    page: "/ar/pages/our-story-new";
  } | {
    id: "routes/pages.our-story-new";
    page: "/pages/our-story-new";
  };
  "routes/pages.mls-affiliate.tsx": {
    id: "ar-pages-affiliate";
    page: "/ar/pages/mls-affiliate";
  } | {
    id: "routes/pages.mls-affiliate";
    page: "/pages/mls-affiliate";
  };
  "routes/pages.delivery-info.tsx": {
    id: "ar-pages-delivery";
    page: "/ar/pages/delivery-info";
  } | {
    id: "routes/pages.delivery-info";
    page: "/pages/delivery-info";
  };
  "routes/pages.subscription-policy.tsx": {
    id: "ar-pages-sub-policy";
    page: "/ar/pages/subscription-policy";
  } | {
    id: "routes/pages.subscription-policy";
    page: "/pages/subscription-policy";
  };
  "routes/pages.subscriptions.tsx": {
    id: "ar-pages-subscriptions";
    page: "/ar/pages/subscriptions";
  } | {
    id: "routes/pages.subscriptions";
    page: "/pages/subscriptions";
  };
  "routes/pages.subscription.tsx": {
    id: "ar-pages-subscription";
    page: "/ar/pages/subscription";
  } | {
    id: "routes/pages.subscription";
    page: "/pages/subscription";
  };
  "routes/pages.$handle.tsx": {
    id: "ar-pages-handle";
    page: "/ar/pages/:handle";
  } | {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/ar.$.tsx": {
    id: "routes/ar.$";
    page: "/ar/*";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/cart[.]js.tsx": {
    id: "routes/cart[.]js";
    page: "/cart.js";
  };
  "routes/apps.loggedincustomer.tsx": {
    id: "routes/apps.loggedincustomer";
    page: "/apps/loggedincustomer";
  };
  "routes/api.reviews.store.tsx": {
    id: "routes/api.reviews.store";
    page: "/api/reviews/store";
  };
  "routes/api.reviews.$handle.tsx": {
    id: "routes/api.reviews.$handle";
    page: "/api/reviews/:handle";
  };
  "routes/api.selling-plans.$handle.tsx": {
    id: "routes/api.selling-plans.$handle";
    page: "/api/selling-plans/:handle";
  };
  "routes/api.globo-options.$productId.tsx": {
    id: "routes/api.globo-options.$productId";
    page: "/api/globo-options/:productId";
  };
  "routes/api.back-in-stock.tsx": {
    id: "routes/api.back-in-stock";
    page: "/api/back-in-stock";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/authorize" | "/account/logout";
  };
  "routes/account._index.tsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/laptechpk/Hydrogen-Live/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "ar-index": typeof import("./app/routes/ar._index.tsx");
  "ar-collections-handle": typeof import("./app/routes/collections.$handle.tsx");
  "ar-products-handle": typeof import("./app/routes/products.$handle.tsx");
  "ar-search": typeof import("./app/routes/search.tsx");
  "ar-blogs-all": typeof import("./app/routes/blogs.all.tsx");
  "ar-blogs-handle": typeof import("./app/routes/blogs.$handle.tsx");
  "ar-blogs-article": typeof import("./app/routes/blogs.$blogHandle.$articleHandle.tsx");
  "ar-pages-customer-reviews": typeof import("./app/routes/pages.customer-reviews.tsx");
  "ar-pages-contact": typeof import("./app/routes/pages.contact.tsx");
  "ar-pages-refund": typeof import("./app/routes/pages.refund-exchange.tsx");
  "ar-pages-rewards": typeof import("./app/routes/pages.rewards.tsx");
  "ar-pages-mls-rewards": typeof import("./app/routes/pages.mls-rewards.tsx");
  "ar-pages-all-blog": typeof import("./app/routes/pages.all-blog.tsx");
  "ar-pages-refer": typeof import("./app/routes/pages.refer-a-friend.tsx");
  "ar-pages-faqs": typeof import("./app/routes/pages.faqs.tsx");
  "ar-pages-gourmet": typeof import("./app/routes/pages.mls-gourmet.tsx");
  "ar-pages-our-story": typeof import("./app/routes/pages.our-story-new.tsx");
  "ar-pages-affiliate": typeof import("./app/routes/pages.mls-affiliate.tsx");
  "ar-pages-delivery": typeof import("./app/routes/pages.delivery-info.tsx");
  "ar-pages-sub-policy": typeof import("./app/routes/pages.subscription-policy.tsx");
  "ar-pages-subscriptions": typeof import("./app/routes/pages.subscriptions.tsx");
  "ar-pages-subscription": typeof import("./app/routes/pages.subscription.tsx");
  "ar-pages-handle": typeof import("./app/routes/pages.$handle.tsx");
  "routes/ar.$": typeof import("./app/routes/ar.$.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/cart[.]js": typeof import("./app/routes/cart[.]js.tsx");
  "routes/apps.loggedincustomer": typeof import("./app/routes/apps.loggedincustomer.tsx");
  "search": typeof import("./app/routes/search.tsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.tsx");
  "routes/blogs.all": typeof import("./app/routes/blogs.all.tsx");
  "routes/blogs.$handle": typeof import("./app/routes/blogs.$handle.tsx");
  "routes/blogs.$blogHandle.$articleHandle": typeof import("./app/routes/blogs.$blogHandle.$articleHandle.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/api.reviews.store": typeof import("./app/routes/api.reviews.store.tsx");
  "routes/api.reviews.$handle": typeof import("./app/routes/api.reviews.$handle.tsx");
  "routes/api.selling-plans.$handle": typeof import("./app/routes/api.selling-plans.$handle.tsx");
  "routes/api.globo-options.$productId": typeof import("./app/routes/api.globo-options.$productId.tsx");
  "routes/api.back-in-stock": typeof import("./app/routes/api.back-in-stock.tsx");
  "routes/pages.customer-reviews": typeof import("./app/routes/pages.customer-reviews.tsx");
  "routes/pages.contact": typeof import("./app/routes/pages.contact.tsx");
  "routes/pages.refund-exchange": typeof import("./app/routes/pages.refund-exchange.tsx");
  "routes/pages.rewards": typeof import("./app/routes/pages.rewards.tsx");
  "routes/pages.mls-rewards": typeof import("./app/routes/pages.mls-rewards.tsx");
  "routes/pages.all-blog": typeof import("./app/routes/pages.all-blog.tsx");
  "routes/pages.refer-a-friend": typeof import("./app/routes/pages.refer-a-friend.tsx");
  "routes/pages.faqs": typeof import("./app/routes/pages.faqs.tsx");
  "routes/pages.mls-gourmet": typeof import("./app/routes/pages.mls-gourmet.tsx");
  "routes/pages.our-story-new": typeof import("./app/routes/pages.our-story-new.tsx");
  "routes/pages.mls-affiliate": typeof import("./app/routes/pages.mls-affiliate.tsx");
  "routes/pages.delivery-info": typeof import("./app/routes/pages.delivery-info.tsx");
  "routes/pages.subscription-policy": typeof import("./app/routes/pages.subscription-policy.tsx");
  "routes/pages.subscriptions": typeof import("./app/routes/pages.subscriptions.tsx");
  "routes/pages.subscription": typeof import("./app/routes/pages.subscription.tsx");
  "routes/pages.$handle": typeof import("./app/routes/pages.$handle.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account._index": typeof import("./app/routes/account._index.tsx");
  "routes/account_.authorize": typeof import("./app/routes/account_.authorize.tsx");
  "routes/account_.logout": typeof import("./app/routes/account_.logout.tsx");
  "/Users/laptechpk/Hydrogen-Live/hydrogen/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};